In [1]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout, BatchNormalization
from keras.callbacks import TensorBoard
import keras
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score
import numpy as np


In [2]:
start_limit = 0
end_limit = 33000

X=np.load('/kaggle/input/first60sortedconcat/first60SortedConcat.npy')
# X = X[start_limit:end_limit]

Y=np.load('/kaggle/input/allarrays100/all_labels.npy')
Y = Y[start_limit:end_limit]

In [3]:
# new_X = []
# new_Y = []

# i = 0
# while i < X.shape[0]:
#     for j in range(15):
#         new_X.append(X[i+j])
#         new_Y.append(Y[i+j])
#     i += 55

# X = np.array(new_X)
# Y = np.array(new_Y)

In [4]:
actions=['about', 'accident', 'africa', 'afternoon', 'again', 'all', 'always', 'animal', 'any', 'apple', 'approve', 'argue', 'arrive', 'aunt', 'baby', 'back', 'bake', 'balance', 'bald', 'ball', 'banana', 'bar', 'basement', 'basketball', 'bath', 'bathroom', 'bear', 'beard', 'bed', 'bedroom', 'before', 'better', 'bicycle', 'bird', 'birthday', 'bitter', 'black', 'blue', 'book', 'both', 'bowl', 'bowling', 'box', 'boy', 'boyfriend', 'bring', 'brother', 'brown', 'business', 'but', 'buy', 'can', 'candy', 'car', 'cards', 'cat', 'catch', 'center', 'cereal', 'chair', 'change', 'check', 'cheese', 'chicken', 'children', 'christmas', 'church', 'city', 'class', 'classroom', 'clock', 'clothes', 'coffee', 'cold', 'college', 'color', 'computer', 'cook', 'cookie', 'cool', 'copy', 'corn', 'cough', 'country', 'cousin', 'cow', 'crash', 'crazy', 'cute', 'dance', 'dark', 'day', 'deaf', 'decide', 'dentist', 'dictionary', 'different', 'dirty', 'discuss', 'doctor', 'dog', 'doll', 'door', 'draw', 'drink', 'easy', 'eat', 'elevator', 'enjoy', 'enter', 'environment', 'exercise', 'experience', 'face', 'family', 'far', 'fat', 'feel', 'fine', 'finish', 'first', 'fish', 'fishing', 'food', 'football', 'forget', 'friend', 'friendly', 'from', 'full', 'future', 'game', 'give', 'glasses', 'go', 'graduate', 'greece', 'green', 'hair', 'halloween', 'happy', 'hat', 'have', 'headache', 'hearing', 'help', 'here', 'home', 'hospital', 'hot', 'house', 'how', 'husband', 'interest', 'internet', 'investigate', 'jacket', 'jump', 'kiss', 'knife', 'know', 'language', 'last', 'last year', 'later', 'law', 'learn', 'letter', 'library', 'like', 'list', 'lose', 'lunch', 'magazine', 'man', 'many', 'match', 'mean', 'meat', 'medicine', 'meet', 'meeting', 'money', 'moon', 'more', 'most', 'mother', 'movie', 'music', 'name', 'need', 'neighbor', 'nephew', 'never', 'nice', 'niece', 'no', 'none', 'noon', 'north', 'not', 'now', 'nurse', 'off', 'ok', 'old', 'opinion', 'orange', 'order', 'paint', 'paper', 'pencil', 'people', 'perspective', 'phone', 'pink', 'pizza', 'plan', 'play', 'please', 'police', 'potato', 'practice', 'president', 'pull', 'purple', 'rabbit', 'rain', 'read', 'red', 'remember', 'restaurant', 'ride', 'run', 'sad', 'school', 'science', 'secretary', 'sentence', 'share', 'shirt', 'shoes', 'shop', 'sick', 'sign', 'since', 'sister', 'sleep', 'slow', 'small', 'smile', 'snow', 'some', 'son', 'sorry', 'south', 'star', 'straight', 'strange', 'struggle', 'student', 'study', 'sunday', 'suspect', 'sweetheart', 'table', 'tall', 'tea', 'teacher', 'tent', 'test', 'thank you', 'thanksgiving', 'thin', 'think', 'thirsty', 'thursday', 'tiger', 'time', 'tired', 'toast', 'together', 'toilet', 'tomorrow', 'traffic', 'travel', 'tree', 'truck', 'uncle', 'use', 'visit', 'wait', 'walk', 'want', 'war', 'water', 'weak', 'wednesday', 'week', 'what', 'when', 'where', 'which', 'white', 'who', 'why', 'wife', 'win', 'wind', 'window', 'with', 'woman', 'work', 'world', 'worry', 'write', 'wrong', 'year', 'yellow', 'yes', 'yesterday', 'you']
actions = actions[:100]

In [5]:
y = to_categorical(Y).astype(int)
# y = y[:,:]
print(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05)
print(X.shape)
print(y.shape)


[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]
(33000, 50, 258)
(33000, 60)


In [6]:
del X
del Y

In [7]:
# model = Sequential()
# model.add(LSTM(64, return_sequences=True, activation='relu', input_shape=(50,258)))
# model.add(LSTM(128, return_sequences=True, activation='relu'))
# model.add(LSTM(64, return_sequences=False, activation='relu'))
# model.add(Dense(64, activation='relu'))
# model.add(Dense(32, activation='relu'))
# model.add(Dense(10, activation='softmax')) #action.shape[0]

model = Sequential()
model.add(LSTM(128, return_sequences=True, activation='relu', input_shape=(50,258)))
# model.add(Dropout(0.2))
# model.add(LSTM(128, return_sequences=True, activation='relu'))
# model.add(Dropout(0.2))
# model.add(LSTM(128, return_sequences=True, activation='relu'))
model.add(Dropout(0.2))
model.add(LSTM(256, return_sequences=True, activation='relu'))
model.add(Dropout(0.2))
model.add(LSTM(256, return_sequences=True, activation='relu'))
model.add(Dropout(0.2))
model.add(LSTM(256, return_sequences=False, activation='relu'))

model.add(BatchNormalization())

# model.add(Dense(256, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))

model.add(Dense(60, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 50, 128)           198144    
                                                                 
 dropout (Dropout)           (None, 50, 128)           0         
                                                                 
 lstm_1 (LSTM)               (None, 50, 256)           394240    
                                                                 
 dropout_1 (Dropout)         (None, 50, 256)           0         
                                                                 
 lstm_2 (LSTM)               (None, 50, 256)           525312    
                                                                 
 dropout_2 (Dropout)         (None, 50, 256)           0         
                                                                 
 lstm_3 (LSTM)               (None, 256)               5

In [ ]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])
callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=8, restore_best_weights=True)

model.fit(X_train, y_train,validation_data=(X_test,y_test), epochs=600, callbacks=[callback],batch_size=128)

Epoch 1/600
245/245 [==============================] - 113s 412ms/step - loss: 3.3523 - categorical_accuracy: 0.1123 - val_loss: 3.4851 - val_categorical_accuracy: 0.1424
Epoch 2/600
245/245 [==============================] - 98s 400ms/step - loss: 1.9442 - categorical_accuracy: 0.3988 - val_loss: 2.2027 - val_categorical_accuracy: 0.3988
Epoch 3/600
245/245 [==============================] - 98s 402ms/step - loss: 1.1035 - categorical_accuracy: 0.6417 - val_loss: 1.8767 - val_categorical_accuracy: 0.4230
Epoch 4/600
245/245 [==============================] - 94s 383ms/step - loss: 0.5692 - categorical_accuracy: 0.8231 - val_loss: 0.6433 - val_categorical_accuracy: 0.7921
Epoch 5/600
245/245 [==============================] - 94s 384ms/step - loss: 0.3544 - categorical_accuracy: 0.8912 - val_loss: 0.6994 - val_categorical_accuracy: 0.7855
Epoch 6/600
245/245 [==============================] - 93s 379ms/step - loss: 0.2425 - categorical_accuracy: 0.9258 - val_loss: 0.6273 - val_categori

In [ ]:

# checkpoint_filepath='/content/savedweights'
# model_checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
#     filepath=checkpoint_filepath,
#     save_weights_only=True,
#     monitor='categorical_accuracy',
#     mode='max',
#     save_best_only=True)
# callback = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=30, restore_best_weights=True)
# from tensorflow.keras.callbacks import EarlyStopping
# early_stopping_monitor = EarlyStopping(patience = 40)

In [ ]:
model.save('60C_50F_128B_5T_sorted.h5')
# del model, X_train, X_test, y_train, y_test

In [ ]:
yhat = model.predict(X_test)
ytrue = np.argmax(y_test, axis=1).tolist()
yhat = np.argmax(yhat, axis=1).tolist()
multilabel_confusion_matrix(ytrue, yhat)

In [ ]:
accuracy_score(ytrue, yhat)